CREATE TABLE continents (
    -- Lista de continentes conocidos, con algunos detalles.
    continent_ID SERIAL PRIMARY KEY, 
    continent_iso_type_code VARCHAR(2), 
    continent_name VARCHAR(13) UNIQUE NOT NULL, -- Este límite es aparente, ya que se basa en el más largo de la lista. Pueden cambiarlo si existe uno más largo en el futuro.
    observation TEXT, 
    is_active BOOLEAN DEFAULT TRUE
);

INSERT INTO continents (continent_iso_type_code, continent_name, observation) 
VALUES 
    ('SA', 'Sudamérica', 'Continente que abarca América del Sur.'), 
    ('NA', 'Norteamérica', 'Incluye países como EE.UU., Canadá y México.'), 
    ('EU', 'Europa', 'Desde Portugal hasta Rusia.'), 
    ('AS', 'Asia', 'Incluye China, Japón, India, etc.'), 
    ('CA', 'Centroamérica', 'Zona que conecta América del Norte y del Sur.'), 
    ('OC', 'Oceanía', 'Incluye Australia, Nueva Zelanda y otras islas.'), 
    ('AF', 'África', 'Continente de gran diversidad geográfica y cultural.'), 
    ('AN', 'Antártida', 'Región polar sin población permanente.'); 
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE countries (
    -- Lista para países/macro-territorios/islas con subdivisiones o provincias
    country_ID SERIAL PRIMARY KEY, 
    country_iso_type_code VARCHAR(7) UNIQUE,
    country_name VARCHAR(44) NOT NULL, -- Este límite es aparente, ya que se basa en el más largo de la lista. Pueden cambiarlo si existe uno más largo en el futuro.
    country_continent INTEGER NOT NULL, 
    observation TEXT, 
    is_sovereign BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (country_continent) REFERENCES continents(continent_ID)
);

INSERT INTO countries (country_iso_type_code, country_name, continent_id, observation, is_sovereign)
VALUES 
    -- Países de Sudamérica (18 países)
        -- Soberanos (14 países)
            ('ARG', 'Argentina', 1, '', TRUE), 
            ('BOL', 'Bolivia', 1, '', TRUE), 
            ('BRA', 'Brasil', 1, '', TRUE), 
            ('CHL', 'Chile', 1, '', TRUE), 
            ('COL', 'Colombia', 1, '', TRUE), 
            ('ECU', 'Ecuador', 1, '', TRUE), 
            ('GRD', 'Granada/Gwenad/La Gwinad', 1, '', TRUE), 
            ('GUY', 'Guyana', 1, '', TRUE), 
            ('PRY', 'Paraguay', 1, '', TRUE), 
            ('PER', 'Perú', 1, '', TRUE), 
            ('SUR', 'Surinam/Suriname', 1, '', TRUE), 
            ('TTO', 'Trinidad y Tobago', 1, '', TRUE), 
            ('URY', 'Uruguay', 1, '', TRUE), 
            ('VEN', 'Venezuela', 1, '', TRUE), 
        -- No Soberanos (4 países)
            ('GUF', 'Guayana Francesa/Guyane/Guyane française', 1, 'Territorio de Francia'), 
            ('SGS', 'Islas Georgias del Sur y Sandwich del Sur', 1, 'Territorio del Reino Unido'), 
            ('FLK', 'Islas Malvinas', 1, 'Territorio del Reino Unido'), 
            ('SHN', 'Santa Elena, Ascensión y Tristán de Acuña', 1, 'Territorio del Reino Unido'), 

    -- Países de Norteamérica (7 países)
        -- Soberanos (3 países) 
            ('CAN', 'Canadá', 2, '', TRUE), 
            ('USA', 'Estados Unidos', 2, '', TRUE), 
            ('MEX', 'México', 2, '', TRUE), 
        -- No Soberanos (4 países)
            ('BMU', 'Bermudas/Bermuda', 2, 'Territorio del Reino Unido'), 
            ('GRL', 'Groenlandia', 2, 'Territorio de Dinamarca'), 
            ('UMI', 'Islas Ultramarinas Menores de Estados Unidos', 2, 'Territorio de Estados Unidos'), 
            ('SPM', 'San Pedro y Miquelón', 2, 'Territorio de Francia'), 

    -- Países de Europa (52 países)
        -- Soberanos (45 países) 
            ('ALA', 'Åland', 3, '', TRUE), 
            ('ALB', 'Albania', 3, '', TRUE), 
            ('DEU', 'Alemania', 3, '', TRUE), 
            ('AND', 'Andorra', 3, '', TRUE), 
            ('AUT', 'Austria', 3, '', TRUE), 
            ('BEL', 'Bélgica', 3, '', TRUE), 
            ('BLR', 'Belarús/Bielorrusia', 3, '', TRUE), 
            ('BIH', 'Bosnia y Herzegovina', 3, '', TRUE), 
            ('BGR', 'Bulgaria', 3, '', TRUE), 
            ('CZE', 'Chequia/República Checa', 3, '', TRUE), 
            ('CYP', 'Chipre', 3, '', TRUE), 
            ('VAT', 'Ciudad del Vaticano', 3, '', TRUE), 
            ('HRV', 'Croacia', 3, '', TRUE), 
            ('DNK', 'Dinamarca', 3, '', TRUE), 
            ('SVK', 'Eslovaquia', 3, '', TRUE), 
            ('SVN', 'Eslovenia', 3, '', TRUE), 
            ('ESP', 'España', 3, '', TRUE), 
            ('EST', 'Estonia', 3, '', TRUE), 
            ('FIN', 'Finlandia', 3, '', TRUE), 
            ('FRA', 'Francia', 3, '', TRUE), 
            ('GRC', 'Grecia', 3, '', TRUE), 
            ('HUN', 'Hungría', 3, '', TRUE), 
            ('IRL', 'Irlanda', 3, '', TRUE), 
            ('ISL', 'Islandia', 3, '', TRUE), 
            ('ITA', 'Italia', 3, '', TRUE), 
            ('LVA', 'Letonia', 3, '', TRUE), 
            ('LIE', 'Liechtenstein', 3, '', TRUE), 
            ('LTU', 'Lituania', 3, '', TRUE), 
            ('LUX', 'Luxemburgo', 3, '', TRUE), 
            ('MKD', 'Macedonia del Norte', 3, '', TRUE), 
            ('MLT', 'Malta', 3, '', TRUE), 
            ('MDA', 'Moldavia', 3, '', TRUE), 
            ('MCO', 'Mónaco', 3, '', TRUE), 
            ('MNE', 'Montenegro', 3, '', TRUE), 
            ('NOR', 'Noruega', 3, '', TRUE), 
            ('NLD', 'Países Bajos/Holanda', 3, '', TRUE), 
            ('POL', 'Polonia', 3, '', TRUE), 
            ('PRT', 'Portugal', 3, '', TRUE), 
            ('GBR', 'Reino Unido', 3, '', TRUE), 
            ('ROU', 'Rumanía', 3, '', TRUE), 
            ('SMR', 'San Marino', 3, '', TRUE), 
            ('SRB', 'Serbia', 3, '', TRUE), 
            ('SWE', 'Suecia', 3, '', TRUE), 
            ('CHE', 'Suiza', 3, '', TRUE), 
            ('UKR', 'Ucrania', 3, '', TRUE), 
        -- No Soberanos (7 países)
            ('GIB', 'Gibraltar', 3, 'Territorio del Reino Unido'), 
            ('GGY', 'Guernsey', 3, 'Dependencia de la Corona Británica'), 
            ('IMN', 'Isla de Man', 3, 'Dependencia de la Corona Británica'), 
            ('FRO', 'Islas Feroe', 3, 'Territorio de Dinamarca'), 
            ('JEY', 'Jersey', 3, 'Dependencia de la Corona Británica'), 
            ('SJM', 'Svalbard y Jan Mayen', 3, 'Territorio de Noruega'), 
            ('RKS/KOS', 'Kosovo/Kósovo', 3, 'República con Soberanía discutida. Reconocido por ~100 países, relevante en los Balcanes.'), 

    -- Países de Asia (60 países)
        -- Soberanos (54 países)
            ('AFG', 'Afganistán', 4, '', TRUE), 
            ('SAU', 'Arabia Saudita', 4, '', TRUE), 
            ('ARM', 'Armenia', 4, '', TRUE), 
            ('AZE', 'Azerbaiyán', 4, '', TRUE), 
            ('BHR', 'Baréin', 4, '', TRUE), 
            ('BGD', 'Bangladés', 4, '', TRUE), 
            ('BRN', 'Brunéi', 4, '', TRUE), 
            ('BTN', 'Bután', 4, '', TRUE), 
            ('KHM', 'Camboya', 4, '', TRUE), 
            ('QAT', 'Catar', 4, '', TRUE), 
            ('CHN', 'China', 4, '', TRUE), 
            ('PRK', 'Corea del Norte', 4, '', TRUE), 
            ('KOR', 'Corea del Sur', 4, '', TRUE), 
            ('ARE', 'Emiratos Árabes Unidos', 4, '', TRUE), 
            ('PHL', 'Filipinas', 4, '', TRUE), 
            ('GEO', 'Georgia', 4, '', TRUE), 
            ('IND', 'India', 4, '', TRUE), 
            ('IDN', 'Indonesia', 4, '', TRUE), 
            ('IRQ', 'Irak', 4, '', TRUE), 
            ('IRN', 'Irán', 4, '', TRUE), 
            ('ISR', 'Israel', 4, '', TRUE), 
            ('JPN', 'Japón', 4, '', TRUE), 
            ('JOR', 'Jordania', 4, '', TRUE), 
            ('KAZ', 'Kazajistán', 4, '', TRUE), 
            ('KGZ', 'Kirguistán', 4, '', TRUE), 
            ('KIR', 'Kiribati', 4, '', TRUE), 
            ('KWT', 'Kuwait', 4, '', TRUE), 
            ('LAO', 'Laos', 4, '', TRUE), 
            ('LBN', 'Líbano', 4, '', TRUE), 
            ('MYS', 'Malasia', 4, '', TRUE), 
            ('MDV', 'Maldivas', 4, '', TRUE), 
            ('FSM', 'Micronesia', 4, '', TRUE), 
            ('MNG', 'Mongolia', 4, '', TRUE), 
            ('MMR', 'Myanmar/Birmania', 4, '', TRUE), 
            ('NRU', 'Nauru', 4, '', TRUE), 
            ('NPL', 'Nepal', 4, '', TRUE), 
            ('OMN', 'Omán', 4, '', TRUE), 
            ('PAK', 'Pakistán', 4, '', TRUE), 
            ('PLW', 'Palaos', 4, '', TRUE), 
            ('PSE', 'Palestina', 4, '', TRUE), 
            ('PNG', 'Papúa Nueva Guinea', 4, '', TRUE), 
            ('RUS', 'Rusia', 4, '', TRUE), 
            ('SGP', 'Singapur', 4, '', TRUE), 
            ('SYR', 'Siria', 4, '', TRUE), 
            ('LKA', 'Sri Lanka', 4, '', TRUE), 
            ('THA', 'Tailandia', 4, '', TRUE), 
            ('TWN', 'Taiwán', 4, '', TRUE), 
            ('TJK', 'Tayikistán', 4, '', TRUE), 
            ('TKM', 'Turkmenistán', 4, '', TRUE), 
            ('TUR', 'Turquía', 4, '', TRUE), 
            ('TUV', 'Tuvalu', 4, '', TRUE), 
            ('UZB', 'Uzbekistán', 4, '', TRUE), 
            ('VNM', 'Vietnam', 4, '', TRUE), 
            ('YEM', 'Yemen', 4, '', TRUE), 
        -- No Soberanos (6 países)
            ('GUM', 'Guam', 4, 'Territorio de Estados Unidos'), 
            ('HKG', 'Hong Kong', 4, 'Región Administrativa Especial de China'), 
            ('MNP', 'Islas Marianas del Norte', 4, 'Territorio de Estados Unidos'), 
            ('MAC', 'Macao', 4, 'Región Administrativa Especial de China'), 
            ('NIU', 'Niue', 4, 'Estado asociado a Nueva Zelanda'), 
            ('IOT', 'Territorio Británico del Océano Índico', 4, 'Base militar del Reino Unido'), 

    -- Países de Centroamérica (35 países)
        -- Soberanos (18 países)
            ('ATG', 'Antigua y Barbuda', 5, '', TRUE), 
            ('BHS', 'Bahamas', 5, '', TRUE), 
            ('BRB', 'Barbados', 5, '', TRUE), 
            ('BLZ', 'Belice', 5, '', TRUE), 
            ('CRI', 'Costa Rica', 5, '', TRUE), 
            ('CUB', 'Cuba', 5, '', TRUE), 
            ('DMA', 'Dominica', 5, '', TRUE), 
            ('SLV', 'El Salvador', 5, '', TRUE), 
            ('GTM', 'Guatemala', 5, '', TRUE), 
            ('HTI', 'Haití', 5, '', TRUE), 
            ('HND', 'Honduras', 5, '', TRUE), 
            ('JAM', 'Jamaica', 5, '', TRUE), 
            ('NIC', 'Nicaragua', 5, '', TRUE), 
            ('PAN', 'Panamá', 5, '', TRUE), 
            ('DOM', 'República Dominicana', 5, '', TRUE), 
            ('KNA', 'San Cristóbal y Nieves', 5, '', TRUE),
            ('VCT', 'San Vicente y las Granadinas', 5, '', TRUE), 
            ('LCA', 'Santa Lucía', 5, '', TRUE), 
        -- No Soberanos (17 países)
            ('AIA', 'Anguila', 5, 'Territorio del Reino Unido'), 
            ('ABW', 'Aruba', 5, 'País autónomo de Países Bajos'), 
            ('BES', 'Bonaire', 5, 'Municipio especial de Países Bajos'), 
            ('CUW', 'Curazao', 5, 'País autónomo de Países Bajos'), 
            ('GLP', 'Guadalupe', 5, 'Territorio de Francia'), 
            ('CYM', 'Islas Caimán', 5, 'Territorio del Reino Unido'), 
            ('TCA', 'Islas Turcas y Caicos', 5, 'Territorio del Reino Unido'), 
            ('VGB', 'Islas Vírgenes Británicas', 5, 'Territorio del Reino Unido'), 
            ('VIR', 'Islas Vírgenes de los Estados Unidos', 5, 'Territorio de Estados Unidos'), 
            ('MTQ', 'Martinica', 5, 'Territorio de Francia'), 
            ('MSR', 'Montserrat', 5, 'Territorio del Reino Unido'), 
            ('PRI', 'Puerto Rico', 5, 'Territorio de Estados Unidos'), 
            ('BES', 'Saba', 5, 'Municipio especial de Países Bajos'), 
            ('BLM', 'San Bartolomé (Francia)', 5, 'Territorio de Francia'), 
            ('BES', 'San Eustaquio', 5, 'Municipio especial de Países Bajos'), 
            ('MAF', 'San Martín (Francia)', 5, 'Territorio de Francia'), 
            ('SXM', 'San Martín (Países Bajos/Holanda)', 5, 'País autónomo de Países Bajos'), 

    -- Países de Oceanía (20 países)
        -- Soberanos (10 países)
            ('AUS', 'Australia', 6, '', TRUE), 
            ('FJI', 'Fiyi', 6, '', TRUE), 
            ('COK', 'Islas Cook', 6, '', TRUE), 
            ('MHL', 'Islas Marshall', 6, '', TRUE), 
            ('SLB', 'Islas Salomón', 6, '', TRUE), 
            ('NZL', 'Nueva Zelanda', 6, '', TRUE), 
            ('WSM', 'Samoa', 6, '', TRUE), 
            ('TLS', 'Timor Oriental', 6, '', TRUE), 
            ('TON', 'Tonga', 6, '', TRUE), 
            ('VUT', 'Vanuatu', 6, '', TRUE), 
        -- No Soberanos (10 países)
            ('CXR', 'Isla de Navidad', 6, 'Territorio de Australia'), 
            ('NFK', 'Isla Norfolk', 6, 'Territorio de Australia'), 
            ('', 'Islas Ashmore y Cartier', 6, 'Territorio de Australia'), 
            ('CCK', 'Islas Cocos/Keeling', 6, 'Territorio Australiano'), 
            ('PCN', 'Islas Pitcairn', 6, 'Territorio del Reino Unido'), 
            ('NCL', 'Nueva Caledonia', 6, 'Territorio de Francia'), 
            ('PYF', 'Polinesia Francesa', 6, 'Territorio de Francia'), 
            ('ASM', 'Samoa Americana', 6, 'Territorio de Estados Unidos'), 
            ('TKL', 'Tokelau', 6, 'Territorio de Nueva Zelanda'), 
            ('WLF', 'Wallis y Futuna', 6, 'Territorio de Francia'), 

    -- Países de África (57 países)
        -- Soberanos (54 países)
            ('AGO', 'Angola', 7, '', TRUE), 
            ('DZA', 'Argelia', 7, '', TRUE), 
            ('BEN', 'Benín', 7, '', TRUE), 
            ('BWA', 'Botsuana', 7, '', TRUE), 
            ('BFA', 'Burkina Faso', 7, '', TRUE), 
            ('BDI', 'Burundi', 7, '', TRUE), 
            ('CPV', 'Cabo Verde', 7, '', TRUE), 
            ('CMR', 'Camerún', 7, '', TRUE), 
            ('TCD', 'Chad', 7, '', TRUE), 
            ('COM', 'Comoras', 7, '', TRUE), 
            ('COG', 'Congo', 7, '', TRUE), 
            ('CIV', 'Costa de Marfil', 7, '', TRUE), 
            ('EGY', 'Egipto', 7, '', TRUE), 
            ('ERI', 'Eritrea', 7, '', TRUE), 
            ('ETH', 'Etiopía', 7, '', TRUE), 
            ('GAB', 'Gabón', 7, '', TRUE), 
            ('GMB', 'Gambia', 7, '', TRUE), 
            ('GHA', 'Ghana', 7, '', TRUE), 
            ('GIN', 'Guinea', 7, '', TRUE), 
            ('GNB', 'Guinea-Bisáu', 7, '', TRUE), 
            ('GNQ', 'Guinea Ecuatorial', 7, '', TRUE), 
            ('KEN', 'Kenia', 7, '', TRUE), 
            ('LSO', 'Lesoto', 7, '', TRUE), 
            ('LBR', 'Liberia', 7, '', TRUE), 
            ('LBY', 'Libia', 7, '', TRUE), 
            ('MDG', 'Madagascar', 7, '', TRUE), 
            ('MWI', 'Malaui/Malawi', 7, '', TRUE), 
            ('MLI', 'Malí', 7, '', TRUE), 
            ('MAR', 'Marruecos', 7, '', TRUE), 
            ('MUS', 'Mauricio', 7, '', TRUE), 
            ('MRT', 'Mauritania', 7, '', TRUE), 
            ('MOZ', 'Mozambique', 7, '', TRUE), 
            ('NAM', 'Namibia', 7, '', TRUE), 
            ('NER', 'Níger', 7, '', TRUE), 
            ('NGA', 'Nigeria', 7, '', TRUE), 
            ('CAF', 'República Centroafricana/Centroáfrica', 7, '', TRUE), 
            ('COD', 'República Democrática del Congo', 7, '', TRUE), 
            ('RWA', 'Ruanda', 7, '', TRUE), 
            ('STP', 'Santo Tomé y Príncipe', 7, '', TRUE), 
            ('SEN', 'Senegal', 7, '', TRUE), 
            ('SYC', 'Seychelles', 7, '', TRUE), 
            ('SLE', 'Sierra Leona/Sierra Leone', 7, '', TRUE), 
            ('SOM', 'Somalia', 7, '', TRUE), 
            ('SWZ', 'Suazilandia/Esuatini', 7, '', TRUE), 
            ('ZAF', 'Sudáfrica', 7, '', TRUE), 
            ('SDN', 'Sudán', 7, '', TRUE), 
            ('SSD', 'Sudán del Sur', 7, '', TRUE), 
            ('TZA', 'Tanzania', 7, '', TRUE), 
            ('TGO', 'Togo', 7, '', TRUE), 
            ('TUN', 'Túnez', 7, '', TRUE), 
            ('UGA', 'Uganda', 7, '', TRUE), 
            ('DJI', 'Yibuti', 7, '', TRUE), 
            ('ZMB', 'Zambia', 7, '', TRUE), 
            ('ZWE', 'Zimbabue', 7, '', TRUE), 
        -- No Soberanos (3 países)
            ('MYT', 'Mayotte', 7, 'Territorio de Francia'),  
            ('REU', 'Reunión', 7, 'Territorio de Francia'), 
            ('ESH', 'República Árabe Saharaui Democrática', 7, 'Estado con Soberanía discutida. Reconocida por algunos países, actividad limitada pero relevante en contextos africanos.'); 
------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE states (
    -- Lista de provincias/departamentos/estados/cantones/municipios/subdivisiones/parroquias/sectores/etc. de primer nivel en los países
    state_ID SERIAL PRIMARY KEY, 
    state_iso_type_code VARCHAR(7), 
    state_name VARCHAR(107) NOT NULL, -- Este límite es aparente, ya que se basa en el más largo de la lista. Pueden cambiarlo si existe uno más largo en el futuro.
    state_country INTEGER NOT NULL, 
    observation TEXT, 
    is_active BOOLEAN DEFAULT TRUE, 
    FOREIGN KEY (state_country) REFERENCES countries(country_ID)
);

INSERT INTO states (state_name, state_country, observation)
VALUES 
    -- "Provincias" de Sudamérica
        -- Soberanos
            -- Provincias de Argentina (24 provincias)
                ('Buenos Aires', 1, ''), 
                ('Catamarca', 1, ''), 
                ('Chaco', 1, ''), 
                ('Chubut', 1, ''), 
                ('Ciudad Autónoma de Buenos Aires', 1, ''), 
                ('Corrientes', 1, ''), 
                ('Córdoba', 1, ''), 
                ('Entre Ríos', 1, ''), 
                ('Formosa', 1, ''), 
                ('Jujuy', 1, ''), 
                ('La Pampa', 1, ''), 
                ('La Rioja', 1, ''), 
                ('Mendoza', 1, ''), 
                ('Misiones', 1, ''), 
                ('Neuquén', 1, ''), 
                ('Río Negro', 1, ''), 
                ('Salta', 1, ''), 
                ('San Juan', 1, ''), 
                ('San Luis', 1, ''), 
                ('Santa Cruz', 1, ''), 
                ('Santa Fe', 1, ''), 
                ('Santiago del Estero', 1, ''), 
                ('Tierra del Fuego, Antártida e Islas del Atlántico Sur', 1, ''), 
                ('Tucumán', 1, ''), 
            
            -- Departamentos de Bolivia (9 departamentos)
                ('Beni', 2, ''), 
                ('Chuquisaca', 2, ''), 
                ('Cochabamba', 2, ''), 
                ('La Paz', 2, ''), 
                ('Oruro', 2, ''), 
                ('Pando', 2, ''), 
                ('Potosí', 2, ''), 
                ('Santa Cruz', 2, ''), 
                ('Tarija', 2, ''), 

            -- Unidades Federativas de Brasil (27 unidades federativas)
                ('Acre', 3, ''), 
                ('Alagoas', 3, ''), 
                ('Amapá', 3, ''), 
                ('Amazonas', 3, ''), 
                ('Bahia', 3, ''), 
                ('Ceará', 3, ''), 
                ('Distrito Federal', 3, ''), 
                ('Espírito Santo', 3, ''), 
                ('Goiás', 3, ''), 
                ('Maranhão', 3, ''), 
                ('Mato Grosso', 3, ''), 
                ('Mato Grosso do Sul ', 3, ''), 
                ('Minas Gerais', 3, ''), 
                ('Paraná', 3, ''), 
                ('Paraíba', 3, ''), 
                ('Pará', 3, ''), 
                ('Pernambuco', 3, ''), 
                ('Piauí', 3, ''), 
                ('Rio de Janeiro', 3, ''), 
                ('Rio Grande do Norte', 3, ''), 
                ('Rio Grande do Sul', 3, ''), 
                ('Rondônia', 3, ''), 
                ('Roraima', 3, ''), 
                ('Santa Catarina', 3, ''), 
                ('Sergipe', 3, ''), 
                ('São Paulo', 3, ''), 
                ('Tocantins', 3, ''), 
            
            -- Regiones de Chile (16 regiones)
                ('Aisén del General Carlos Ibañez del Campo', 4, ''), 
                ('Antofagasta', 4, ''), 
                ('Arica y Parinacota', 4, ''), 
                ('Atacama', 4, ''), 
                ('Biobío', 4, ''), 
                ('Coquimbo', 4, ''), 
                ('La Araucanía', 4, ''), 
                ('Libertador General Bernardo O´Higgins', 4, ''), 
                ('Los Lagos', 4, ''), 
                ('Los Ríos', 4, ''), 
                ('Magallanes y de la Antártica Chilena', 4, ''), 
                ('Maule', 4, ''), 
                ('Región Metropolitana de Santiago', 4, ''), 
                ('Tarapacá', 4, ''), 
                ('Valparaíso', 4, ''), 
                ('Ñuble', 4, ''), 
            
            -- Departamentos de Colombia (33 departamentos)
                ('Amazonas', 5, ''), 
                ('Antioquia', 5, ''), 
                ('Arauca', 5, ''), 
                ('Atlántico', 5, ''), 
                ('Bogotá', 5, ''), 
                ('Bolívar', 5, ''), 
                ('Boyacá', 5, ''), 
                ('Caldas', 5, ''), 
                ('Caquetá', 5, ''), 
                ('Casanare', 5, ''), 
                ('Cauca', 5, ''), 
                ('Cesar', 5, ''), 
                ('Chocó', 5, ''), 
                ('Cundinamarca', 5, ''), 
                ('Córdoba', 5, ''), 
                ('Guainía', 5, ''), 
                ('Guaviare', 5, ''), 
                ('Huila', 5, ''), 
                ('La Guajira', 5, ''), 
                ('Magdalena', 5, ''), 
                ('Meta', 5, ''), 
                ('Nariño', 5, ''), 
                ('Norte de Santander', 5, ''), 
                ('Putumayo', 5, ''), 
                ('Quindío', 5, ''), 
                ('Risaralda', 5, ''), 
                ('San Andrés & Providencia', 5, ''), 
                ('Santander', 5, ''), 
                ('Sucre', 5, ''), 
                ('Tolima', 5, ''), 
                ('Valle del Cauca', 5, ''), 
                ('Vaupés', 5, ''), 
                ('Vichada', 5, ''), 

            -- Provincias de Ecuador (24 provincias)
                ('Azuay', 6, ''), 
                ('Bolívar', 6, ''), 
                ('Carchi', 6, ''), 
                ('Cañar', 6, ''), 
                ('Chimborazo', 6, ''), 
                ('Cotopaxi', 6, ''), 
                ('El Oro', 6, ''), 
                ('Esmeraldas', 6, ''), 
                ('Galápagos', 6, ''), 
                ('Guayas', 6, ''), 
                ('Imbabura', 6, ''), 
                ('Loja', 6, ''), 
                ('Los Ríos', 6, ''), 
                ('Manabí', 6, ''), 
                ('Morona-Santiago', 6, ''), 
                ('Napo', 6, ''), 
                ('Orellana', 6, ''), 
                ('Pastaza', 6, ''), 
                ('Pichincha', 6, ''), 
                ('Santa Elena', 6, ''), 
                ('Santo Domingo de los Tsáchilas', 6, ''), 
                ('Sucumbíos', 6, ''), 
                ('Tungurahua', 6, ''), 
                ('Zamora-Chinchipe', 6, ''), 

            -- Parroquias & Territorios de Granada (14)
                ('Isla Caille', 7, ''), 
                ('Isla de Carriacou/Cariobacú', 7, ''), 
                ('Isla Diamante', 7, ''), 
                ('Isla Frigate', 7, ''), 
                ('Isla Larga', 7, ''), 
                ('Isla Ronde', 7, ''), 
                ('Isla Saline', 7, ''), 
                ('Petite Martinique/Pequeña Martinica', 7, ''), 
                ('Saint Andrew', 7, 'Parroquia'), 
                ('Saint David', 7, 'Parroquia'), 
                ('Saint George', 7, 'Parroquia'), 
                ('Saint John', 7, 'Parroquia'), 
                ('Saint Mark', 7, 'Parroquia'), 
                ('Saint Patrick', 7, 'Parroquia'), 

            -- Regiones de Guyana (10 regiones)
                ('Alto Demerara-Berbice', 8, ''), 
                ('Alto Tacutu-Alto Esequibo', 8, ''), 
                ('Barima-Guainí', 8, ''), 
                ('Berbice Oriental-Corentyne', 8, ''), 
                ('Cuyuní-Mazaruní', 8, ''), 
                ('Demerara-Mahaica', 8, ''), 
                ('Islas Esequibo-Demerara Occidental', 8, ''), 
                ('Mahaica-Berbice', 8, ''), 
                ('Pomerón-Supenaam', 8, ''), 
                ('Potaro-Siparuní', 8, ''), 

            -- Departamentos de Paraguay (18 departamentos)
                ('Alto Paraguay', 9, ''), 
                ('Alto Paraná', 9, ''), 
                ('Amambay', 9, ''), 
                ('Asunción', 9, ''), 
                ('Boquerón', 9, ''), 
                ('Caaguazú', 9, ''), 
                ('Caazapá', 9, ''), 
                ('Canindeyú', 9, ''), 
                ('Central', 9, ''), 
                ('Concepción', 9, ''), 
                ('Cordillera', 9, ''), 
                ('Guairá', 9, ''), 
                ('Itapúa', 9, ''), 
                ('Misiones', 9, ''), 
                ('Ñeembucú', 9, ''), 
                ('Paraguarí', 9, ''), 
                ('Presidente Hayes', 9, ''), 
                ('San Pedro', 9, ''), 

            -- Departamentos de Perú (26 departamentos)
                ('Amazonas', 10, ''), 
                ('Áncash', 10, ''), 
                ('Apurímac', 10, ''), 
                ('Arequipa', 10, ''), 
                ('Ayacucho', 10, ''), 
                ('Cajamarca', 10, ''), 
                ('Callao', 10, ''), 
                ('Cuzco', 10, ''), 
                ('Huancavelica', 10, ''), 
                ('Huánuco', 10, ''), 
                ('Ica', 10, ''), 
                ('Junín', 10, ''), 
                ('La Libertad', 10, ''), 
                ('Lambayeque', 10, ''), 
                ('Lima', 10, ''), 
                ('Lima Metropolitana', 10, ''), 
                ('Loreto', 10, ''), 
                ('Madre de Dios', 10, ''), 
                ('Moquegua', 10, ''), 
                ('Pasco', 10, ''), 
                ('Piura', 10, ''), 
                ('Puno', 10, ''), 
                ('San Martín', 10, ''), 
                ('Tacna', 10, ''), 
                ('Tumbes', 10, ''), 
                ('Ucayali', 10, ''), 

            -- Distritos/Districten de Surinam/Suriname (10 distritos)
                ('Brokopondo', 11, ''), 
                ('Commewijne', 11, ''), 
                ('Coronie', 11, ''), 
                ('Marowijne', 11, ''), 
                ('Nickerie', 11, ''), 
                ('Para', 11, ''), 
                ('Paramaribo', 11, ''), 
                ('Saramacca', 11, ''), 
                ('Sipaliwini', 11, ''), 
                ('Wanica', 11, ''), 

            -- Municipios, Regiones & Parroquias de Trinidad y Tobago (21)
                ('Arima', 12, 'Municipio de Trinidad'), 
                ('Chaguanas', 12, 'Municipio de Trinidad'), 
                ('Couva-Tabaquite-Talparo', 12, 'Región de Trinidad'), 
                ('Diego Martín', 12, 'Región de Trinidad'), 
                ('Penal-Debe', 12, 'Región de Trinidad'), 
                ('Point Fortin', 12, 'Municipio de Trinidad'), 
                ('Princes Town', 12, 'Región de Trinidad'), 
                ('Puerto España', 12, 'Municipio de Trinidad'), 
                ('Río Claro-Mayaro', 12, 'Región de Trinidad'), 
                ('San Fernando', 12, 'Municipio de Trinidad'), 
                ('San Juan-Laventille', 12, 'Región de Trinidad'), 
                ('Sangre Grande', 12, 'Región de Trinidad'), 
                ('Siparia', 12, 'Región de Trinidad'), 
                ('St. Andrew', 12, 'Parroquia de Tobago'), 
                ('St. David', 12, 'Parroquia de Tobago'), 
                ('St. George', 12, 'Parroquia de Tobago'), 
                ('St. John', 12, 'Parroquia de Tobago'), 
                ('St. Mary', 12, 'Parroquia de Tobago'), 
                ('St. Patrick', 12, 'Parroquia de Tobago'), 
                ('St. Paul', 12, 'Parroquia de Tobago'), 
                ('Tunapuna-Piarco', 12, 'Región de Trinidad'), 

            -- Departamentos de Uruguay (19 departamentos)
                ('Artigas', 13, ''), 
                ('Canelones', 13, ''), 
                ('Cerro Largo', 13, ''), 
                ('Colonia', 13, ''), 
                ('Durazno', 13, ''), 
                ('Flores', 13, ''), 
                ('Florida', 13, ''), 
                ('Lavalleja', 13, ''), 
                ('Maldonado', 13, ''), 
                ('Montevideo', 13, ''), 
                ('Paysandú', 13, ''), 
                ('Río Negro', 13, ''), 
                ('Rivera', 13, ''), 
                ('Rocha', 13, ''), 
                ('Salto', 13, ''), 
                ('San José', 13, ''), 
                ('Soriano', 13, ''), 
                ('Tacuarembó', 13, ''), 
                ('Treinta y Tres', 13, ''), 

            -- Entidades Federales de Venezuela (25 entidades federales)
                ('Amazonas', 14, ''), 
                ('Anzoátegui', 14, ''), 
                ('Apure', 14, ''), 
                ('Aragua', 14, ''), 
                ('Barinas', 14, ''), 
                ('Bolívar', 14, ''), 
                ('Carabobo', 14, ''), 
                ('Cojedes', 14, ''), 
                ('Delta Amacuro', 14, ''), 
                ('Dependencias federales', 14, ''), 
                ('Distrito Capital', 14, ''), 
                ('Falcón', 14, ''), 
                ('Guárico', 14, ''), 
                ('La Guaira', 14, ''), 
                ('Lara', 14, ''), 
                ('Mérida', 14, ''), 
                ('Miranda', 14, ''), 
                ('Monagas', 14, ''), 
                ('Nueva Esparta', 14, ''), 
                ('Portuguesa', 14, ''), 
                ('Sucre', 14, ''), 
                ('Trujillo', 14, ''), 
                ('Táchira', 14, ''), 
                ('Yaracuy', 14, ''), 
                ('Zulia', 14, ''), 
        -- No Soberanos
            -- Comunas de Guayana Francesa/Guyane/Guyane française (22 comunas)
                ('Apatou', 15, ''), 
                ('Awala-Yalimapo', 15, ''), 
                ('Camopi', 15, ''), 
                ('Cayena', 15, ''), 
                ('Grand-Santi', 15, ''), 
                ('Iracoubo', 15, ''), 
                ('Kourou', 15, ''), 
                ('Macouria', 15, ''), 
                ('Mana', 15, ''), 
                ('Maripasoula', 15, ''), 
                ('Matoury', 15, ''), 
                ('Montsinéry-Tonnegrande', 15, ''), 
                ('Ouanary', 15, ''), 
                ('Papaïchton', 15, ''), 
                ('Régina', 15, ''), 
                ('Remire-Montjoly', 15, ''), 
                ('Roura', 15, ''), 
                ('Saint-Élie', 15, ''), 
                ('Saint-Georges-de-l´Oyapock', 15, ''), 
                ('Saint-Laurent-du-Maroni', 15, ''), 
                ('Saül', 15, ''), 
                ('Sinnamary', 15, ''), 
            
            -- Islas de Islas Georgias del Sur y Sandwich del Sur (31 islas)
                ('Albatros', 16, 'Isla del grupo San Pedro'), 
                ('Annenkov', 16, 'Isla del grupo San Pedro'), 
                ('Bellingshausen', 16, 'Isla Tule del Sur'), 
                ('Bristol', 16, 'Isla Central'), 
                ('Candlemas', 16, 'Isla Candelaria'), 
                ('Cook', 16, 'Isla Tule del Sur'), 
                ('Cooper', 16, 'Isla del grupo San Pedro'), 
                ('Grass', 16, 'Isla del grupo San Pedro'), 
                ('Islas Bienvenido', 16, 'Isla del grupo San Pedro'), 
                ('Islas Kupriyanov', 16, 'Isla del grupo San Pedro'), 
                ('Islas Pickersgill', 16, 'Isla del grupo San Pedro'), 
                ('Islas Willis', 16, 'Isla del grupo San Pedro'), 
                ('Leskov', 16, 'Isla Traverse'), 
                ('McCarthy', 16, 'Isla del grupo San Pedro'), 
                ('Montagu', 16, 'Isla Central'), 
                ('Pájaro', 16, 'Isla del grupo San Pedro'), 
                ('Prión', 16, 'Isla del grupo San Pedro'), 
                ('Roca Negra', 16, 'Islote Aurora'), 
                ('Rocas Clerke', 16, ''), 
                ('Rocas Cormorán', 16, 'Islote Aurora'), 
                ('Rocas Negras', 16, 'Isla del grupo San Pedro'), 
                ('Saddle', 16, 'Isla del grupo San Pedro'), 
                ('Samuel', 16, 'Isla del grupo San Pedro'), 
                ('Saunders', 16, 'Isla Central'), 
                ('Thule/Morrell', 16, 'Isla Tule del Sur'), 
                ('Trinidad', 16, 'Isla del grupo San Pedro'), 
                ('Verde', 16, 'Isla del grupo San Pedro'), 
                ('Vicent', 16, 'Isla del grupo San Pedro'), 
                ('Vindication', 16, 'Isla Candelaria'), 
                ('Visokoi', 16, 'Isla Traverse'), 
                ('Zavodovski', 16, 'Isla Traverse'), 
            
            -- Islas Principales de Islas Malvinas (2 islas principales)
                ('Gran Malvina', 17, ''), 
                ('Isla Soledad', 17, ''), 
            
            -- Unidades Administrativas de Santa Elena, Ascensión y Tristán de Acuña (3 unidades administrativas)
                ('Isla Ascensión', 18, ''), 
                ('Santa Elena', 18, ''), 
                ('Tristán de Acuña', 18, ''), 

    -- Provincias de Norteamérica
        -- Soberanos
            -- Provincias & Territorios de Canadá (13)
                ('Alberta', 19, ''), 
                ('British Columbia', 19, ''), 
                ('Manitoba', 19, ''), 
                ('New Brunswick', 19, ''), 
                ('Newfoundland and Labrador', 19, ''), 
                ('Northwest Territories', 19, ''), 
                ('Nova Scotia', 19, ''), 
                ('Nunavut', 19, ''), 
                ('Ontario', 19, ''), 
                ('Prince Edward Island', 19, ''), 
                ('Québec', 19, ''), 
                ('Saskatchewan', 19, ''), 
                ('Yukon', 19, ''), 
            
            -- Estados de Estados Unidos (51 estados)
                ('Alabama', 20, ''), 
                ('Alaska', 20, ''), 
                ('Arizona', 20, ''), 
                ('Arkansas', 20, ''), 
                ('California', 20, ''), 
                ('Colorado', 20, ''), 
                ('Connecticut', 20, ''), 
                ('Delaware', 20, ''), 
                ('District Of Columbia', 20, ''), 
                ('Florida', 20, ''), 
                ('Georgia', 20, ''), 
                ('Hawaii', 20, ''), 
                ('Idaho', 20, ''), 
                ('Illinois', 20, ''), 
                ('Indiana', 20, ''), 
                ('Iowa', 20, ''), 
                ('Kansas', 20, ''), 
                ('Kentucky', 20, ''), 
                ('Louisiana', 20, ''), 
                ('Maine', 20, ''), 
                ('Maryland', 20, ''), 
                ('Massachusetts', 20, ''), 
                ('Michigan', 20, ''), 
                ('Minnesota', 20, ''), 
                ('Mississippi', 20, ''), 
                ('Missouri', 20, ''), 
                ('Montana', 20, ''), 
                ('Nebraska', 20, ''), 
                ('Nevada', 20, ''), 
                ('New Hampshire', 20, ''), 
                ('New Jersey', 20, ''), 
                ('New Mexico', 20, ''), 
                ('New York', 20, ''), 
                ('North Carolina', 20, ''), 
                ('North Dakota', 20, ''), 
                ('Ohio', 20, ''), 
                ('Oklahoma', 20, ''), 
                ('Oregon', 20, ''), 
                ('Pennsylvania', 20, ''), 
                ('Rhode Island', 20, ''), 
                ('South Carolina', 20, ''), 
                ('South Dakota', 20, ''), 
                ('Tennessee', 20, ''), 
                ('Texas', 20, ''), 
                ('Utah', 20, ''), 
                ('Vermont', 20, ''), 
                ('Virginia', 20, ''), 
                ('Washington', 20, ''), 
                ('West Virginia', 20, ''), 
                ('Wisconsin', 20, ''), 
                ('Wyoming', 20, ''), 
            
            -- Entidades federativas/Estados de México (32 entidades)
                ('Aguascalientes', 21, ''), 
                ('Baja California', 21, ''), 
                ('Baja California Sur', 21, ''), 
                ('Campeche', 21, ''), 
                ('Chiapas', 21, ''), 
                ('Chihuahua', 21, ''), 
                ('Ciudad de México', 21, ''), 
                ('Coahuila de Zaragoza', 21, ''), 
                ('Colima', 21, ''), 
                ('Durango', 21, ''), 
                ('Guanajuato', 21, ''), 
                ('Guerrero', 21, ''), 
                ('Hidalgo', 21, ''), 
                ('Jalisco', 21, ''), 
                ('Michoacán de Ocampo', 21, ''), 
                ('Morelos', 21, ''), 
                ('México', 21, ''), 
                ('Nayarit', 21, ''), 
                ('Nuevo León', 21, ''), 
                ('Oaxaca', 21, ''), 
                ('Puebla', 21, ''), 
                ('Querétaro', 21, ''), 
                ('Quintana Roo', 21, ''), 
                ('San Luis Potosí', 21, ''), 
                ('Sinaloa', 21, ''), 
                ('Sonora', 21, ''), 
                ('Tabasco', 21, ''), 
                ('Tamaulipas', 21, ''), 
                ('Tlaxcala', 21, ''), 
                ('Veracruz de Ignacio de la Llave', 21, ''), 
                ('Yucatán', 21, ''), 
                ('Zacatecas', 21, ''), 
        -- No Soberanos
            -- Parroquias de Bermudas/Bermuda (9 parroquias)
                ('Devonshire', 22, ''), 
                ('Hamilton', 22, ''), 
                ('Paget', 22, ''), 
                ('Pembroke', 22, ''), 
                ('Saint George', 22, ''), 
                ('Sandys', 22, ''), 
                ('Smith', 22, ''), 
                ('Southampton', 22, ''), 
                ('Warwick', 22, ''), 

            -- Municipalidades & Área no incorporada de Groenlandia (6)
                ('Avannaata Kommunia', 23, ''), 
                ('Kalaallit Nunaanni nuna eqqissisimatitaq/Grønlands Nationalpark', 23, ''), 
                ('Kommune Kujalleq', 23, ''), 
                ('Kommune Qeqertalik', 23, ''), 
                ('Kommuneqarfik Sermersooq', 23, ''), 
                ('Qeqqata Kommunia', 23, ''), 

            -- Atolones, Islas & Arrecife de Islas Ultramarinas Menores de Estados Unidos (9)
                ('Baker Island', 24, ''), 
                ('Howland Island', 24, ''), 
                ('Jarvis Island', 24, ''), 
                ('Johnston Atoll', 24, 'Atolón'), 
                ('Kingman Reef', 24, 'Arrecife'), 
                ('Midway Atoll', 24, 'Atolón'), 
                ('Navassa Island', 24, ''), 
                ('Palmyra Atoll', 24, 'Atolón'), 
                ('Wake Island', 24, ''), 

            -- Comunas de San Pedro y Miquelón (2 comunas)
                ('Miquelón-Langlade', 25, ''), 
                ('Saint Pierre', 25, ''), 

    -- Provincias de Europa
        -- Soberanos
            -- Municipios de Åland (16 municipios)
                ('Brändö', 26, ''), 
                ('Eckerö', 26, ''), 
                ('Finström', 26, ''), 
                ('Föglö', 26, ''), 
                ('Geta', 26, ''), 
                ('Hammarland', 26, ''), 
                ('Jomala', 26, ''), 
                ('Kumlinge', 26, ''), 
                ('Kökar', 26, ''), 
                ('Lemland', 26, ''), 
                ('Lumparland', 26, ''), 
                ('Mariehamn', 26, ''), 
                ('Saltvik', 26, ''), 
                ('Sottunga', 26, ''), 
                ('Sund', 26, ''), 
                ('Vardö', 26, ''), 

            -- Condados de Albania (12 condados)
                ('Beratit', 27, ''), 
                ('Dibrës', 27, ''), 
                ('Durrësit', 27, ''), 
                ('Elbasanit', 27, ''), 
                ('Fierit', 27, ''), 
                ('Gjirokastrës', 27, ''), 
                ('Korçës', 27, ''), 
                ('Kukësit', 27, ''), 
                ('Lezhës', 27, ''), 
                ('Shkodrës', 27, ''), 
                ('Tiranës', 27, ''), 
                ('Vlorës', 27, ''), 

            -- Estados federados de Alemania (16 estados)
                ('Baden-Württemberg', 28, ''), 
                ('Bayern', 28, ''), 
                ('Berlin', 28, ''), 
                ('Brandenburg', 28, ''), 
                ('Bremen', 28, ''), 
                ('Hamburg', 28, ''), 
                ('Hessen', 28, ''), 
                ('Mecklenburg-Vorpommern', 28, ''), 
                ('Niedersachsen', 28, ''), 
                ('Nordrhein-Westfalen', 28, ''), 
                ('Rheinland-Pfalz', 28, ''), 
                ('Saarland', 28, ''), 
                ('Sachsen', 28, ''), 
                ('Sachsen-Anhalt', 28, ''), 
                ('Schleswig-Holstein', 28, ''), 
                ('Thüringen', 28, ''), 

            -- Parroquias de Andorra (7 parroquias)
                ('Andorra la Vella', 29, ''), 
                ('Canillo', 29, ''), 
                ('Encamp', 29, ''), 
                ('Escaldes-Engordany', 29, ''), 
                ('La Massana', 29, ''), 
                ('Ordino', 29, ''), 
                ('Sant Julià de Lòria', 29, ''), 

            -- Estados federados de Austria (9 estados)
                ('Burgenland/Őrvidék', 30, ''), 
                ('Kärnten', 30, ''), 
                ('Niederösterreich', 30, ''), 
                ('Oberösterreich', 30, ''), 
                ('Salzburg', 30, ''), 
                ('Steiermark', 30, ''), 
                ('Tirol', 30, ''), 
                ('Vorarlberg', 30, ''), 
                ('Wien', 30, ''), 

            -- Provincias de Bélgica (10 provincias)
                ('Amberes/Antwerpen/Anvers/Antwerpen', 31, ''), 
                ('Brabante Flamenco/Vlaams-Brabant/Brabant flamand/Flämisch-Brabant', 31, ''), 
                ('Brabante Valón/Waals-Brabant/Brabant wallon/Wallonisch-Brabant', 31, ''), 
                ('Flandes Occidental/West-Vlaanderen/Flandre occidentale/Westflandern', 31, ''), 
                ('Flandes Oriental/Oost-Vlaanderen/Flandre orientale/Ostflandern', 31, ''), 
                ('Henao/Henegouwen/Hainaut/Hennegau', 31, ''), 
                ('Lieja/Luik/Liège/Lüttich', 31, ''), 
                ('Limburgo/Limburg/Limbourg', 31, ''), 
                ('Luxemburgo/Luxemburg/Luxembourg', 31, ''), 
                ('Namur/Namen/Namur/Namür', 31, ''), 

            -- Regiones/Óblast de Belarús/Bielorrusia (6 regiones)
                ('Брэ́сцкая во́бласць/Bresckaja vobłaść/Бре́стская о́бласть/Bréstskaya óblast', 32, ''), 
                ('Ві́цебская во́бласць/Vítsebskaya Vóblast', 32, ''), 
                ('Гомельская вобласць/Гомельская область', 32, ''), 
                ('Гро́дзенская во́бласць/Hródzenskaia vóblast/Гро́дненская область/Gródnenskaia óblast', 32, ''), 
                ('Магілёўская вобласць/Могилёвская область', 32, ''), 
                ('Мінск/Mińsk/Минск', 32, ''), 
                ('Мінская вобласць', 32, ''), 

            -- Cantones & Regiones de Bosnia y Herzegovina (17)
                ('Banjalučka/Banja Luka', 33, 'Región de la República Srpska'), 
                ('Bijeljinska', 33, 'Región de la República Srpska'), 
                ('Bosansko-podrinjskog kantona Goražde/Bosansko-podrinjska županija Goražde/Босанско-подрињски кантон Горажде', 33, 'Cantón de la Federación de Bosnia-Herzegovina'), 
                ('Dobojska', 33, 'Región de la República Srpska'), 
                ('Fočanska', 33, 'Región de la República Srpska'), 
                ('Hercegovačko-neretvanski/Hercegovačko-neretvanska/Херцеговачко-неретвански', 33, 'Cantón de la Federación de Bosnia-Herzegovina'), 
                ('Kanton 10/Hercegbosanska', 33, 'Cantón de la Federación de Bosnia-Herzegovina'), 
                ('Posavski/Posavska', 33, 'Cantón de la Federación de Bosnia-Herzegovina'), 
                ('Sarajevo-Romanija/Sokolac', 33, 'Región de la República Srpska'), 
                ('Sarajevo/Vrhbosanska', 33, 'Cantón de la Federación de Bosnia-Herzegovina'), 
                ('Srednjobosanski/Središnja Bosna/Средњобосански', 33, 'Cantón de la Federación de Bosnia-Herzegovina'), 
                ('Trebinjska', 33, 'Región de la República Srpska'), 
                ('Tuzlanski', 33, 'Cantón de la Federación de Bosnia-Herzegovina'), 
                ('Unsko-sanski', 33, 'Cantón de la Federación de Bosnia-Herzegovina'), 
                ('Vlaseninska', 33, 'Región de la República Srpska'), 
                ('Zapadno-hercegovačka/Zapadno-hercegovačka', 33, 'Cantón de la Federación de Bosnia-Herzegovina'), 
                ('Zeničko-dobojski', 33, 'Cantón de la Federación de Bosnia-Herzegovina'), 

            -- Provincias de Bulgaria (28 provincias)
                ('Благоевград', 34, ''), 
                ('Бургас', 34, ''), 
                ('Варна', 34, ''), 
                ('Велико Търново', 34, ''), 
                ('Видин', 34, ''), 
                ('Враца', 34, ''), 
                ('Габрово', 34, ''), 
                ('Добрич', 34, ''), 
                ('Кърджали', 34, ''), 
                ('Кюстендил', 34, ''), 
                ('Ловеч', 34, ''), 
                ('Монтана', 34, ''), 
                ('Пазарджик', 34, ''), 
                ('Перник', 34, ''), 
                ('Плевен', 34, ''), 
                ('Пловдив', 34, ''), 
                ('Разград', 34, ''), 
                ('Русе', 34, ''), 
                ('Силистра', 34, ''), 
                ('Сливен', 34, ''), 
                ('Смолян', 34, ''), 
                ('Софийска', 34, ''), 
                ('София-град', 34, ''), 
                ('Стара Загора', 34, ''), 
                ('Търговище/Tărgovište', 34, ''), 
                ('Хасково', 34, ''), 
                ('Шумен', 34, ''), 
                ('Ямбол', 34, ''), 

            -- Regiones de Chequia/República Checa (14 regiones)
                ('Jihomoravský', 35, ''), 
                ('Jihočeský', 35, ''), 
                ('Karlovarský', 35, ''), 
                ('Královéhradecký', 35, ''), 
                ('Liberecký', 35, ''), 
                ('Moravskoslezský', 35, ''), 
                ('Olomoucký', 35, ''), 
                ('Pardubický', 35, ''), 
                ('Plzeňský', 35, ''), 
                ('Praha', 35, ''), 
                ('Středočeský', 35, ''), 
                ('Vysočina', 35, ''), 
                ('Zlínský', 35, ''), 
                ('Ústecký', 35, ''), 

            -- 
        -- No Soberanos
            -- 
