CREATE TABLE continents (
    -- Lista de continentes conocidos, con algunos detalles.
    continent_ID SERIAL PRIMARY KEY, 
    continent_iso_type_code VARCHAR(2), 
    continent_name VARCHAR(13) UNIQUE NOT NULL, -- Este límite es aparente, ya que se basa en el más largo de la lista. Pueden cambiarlo si existe uno más largo en el futuro.
    observation TEXT, 
    is_active BOOLEAN DEFAULT TRUE
);

INSERT INTO continents (continent_iso_type_code, continent_name, observation) 
VALUES 
    ('SA', 'Sudamérica', 'Continente que abarca América del Sur.'), 
    ('NA', 'Norteamérica', 'Incluye países como EE.UU., Canadá y México.'), 
    ('EU', 'Europa', 'Desde Portugal hasta Rusia.'), 
    ('AS', 'Asia', 'Incluye China, Japón, India, etc.'), 
    ('CA', 'Centroamérica', 'Zona que conecta América del Norte y del Sur.'), 
    ('OC', 'Oceanía', 'Incluye Australia, Nueva Zelanda y otras islas.'), 
    ('AF', 'África', 'Continente de gran diversidad geográfica y cultural.'), 
    ('AN', 'Antártida', 'Región polar sin población permanente.'); 
------------------------------------------------------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE states (
    -- Lista de provincias/departamentos/regiones/cantones/municipios/subdivisiones/parroquias/sectores/etc. de primer nivel en los países
    state_ID SERIAL PRIMARY KEY, 
    state_iso_type_code VARCHAR(7), 
    state_name VARCHAR(53) NOT NULL, -- Este límite es aparente, ya que se basa en el más largo de la lista. Pueden cambiarlo si existe uno más largo en el futuro.
    state_country INTEGER NOT NULL, 
    observation TEXT, 
    is_active BOOLEAN DEFAULT TRUE, 
    FOREIGN KEY (state_country) REFERENCES countries(country_ID)
);

INSERT INTO states (state_iso_type_code, state_name, state_country, observation)
VALUES 
    -- "Provincias" de Sudamérica
        -- Soberanos
            -- Provincias de Argentina (24 provincias)
                ('', 'Buenos Aires                                         ', 1, ''), 
                ('', 'Catamarca                                            ', 1, ''), 
                ('', 'Chaco                                                ', 1, ''), 
                ('', 'Chubut                                               ', 1, ''), 
                ('', 'Ciudad Autónoma de Buenos Aires                      ', 1, ''), 
                ('', 'Corrientes                                           ', 1, ''), 
                ('', 'Córdoba                                              ', 1, ''), 
                ('', 'Entre Ríos                                           ', 1, ''), 
                ('', 'Formosa                                              ', 1, ''), 
                ('', 'Jujuy                                                ', 1, ''), 
                ('', 'La Pampa                                             ', 1, ''), 
                ('', 'La Rioja                                             ', 1, ''), 
                ('', 'Mendoza                                              ', 1, ''), 
                ('', 'Misiones                                             ', 1, ''), 
                ('', 'Neuquén                                              ', 1, ''), 
                ('', 'Río Negro                                            ', 1, ''), 
                ('', 'Salta                                                ', 1, ''), 
                ('', 'San Juan                                             ', 1, ''), 
                ('', 'San Luis                                             ', 1, ''), 
                ('', 'Santa Cruz                                           ', 1, ''), 
                ('', 'Santa Fe                                             ', 1, ''), 
                ('', 'Santiago del Estero                                  ', 1, ''), 
                ('', 'Tierra del Fuego, Antártida e Islas del Atlántico Sur', 1, ''), 
                ('', 'Tucumán                                              ', 1, ''), 
            
            -- Departamentos de Bolivia (9 departamentos)
                ('', 'Beni      ', 2, ''), 
                ('', 'Chuquisaca', 2, ''), 
                ('', 'Cochabamba', 2, ''), 
                ('', 'La Paz    ', 2, ''), 
                ('', 'Oruro     ', 2, ''), 
                ('', 'Pando     ', 2, ''), 
                ('', 'Potosí    ', 2, ''), 
                ('', 'Santa Cruz', 2, ''), 
                ('', 'Tarija    ', 2, ''), 

            -- Unidades Federativas de Brasil (27 unidades federativas)
                ('', 'Acre               ', 3, ''), 
                ('', 'Alagoas            ', 3, ''), 
                ('', 'Amapá              ', 3, ''), 
                ('', 'Amazonas           ', 3, ''), 
                ('', 'Bahia              ', 3, ''), 
                ('', 'Ceará              ', 3, ''), 
                ('', 'Distrito Federal   ', 3, ''), 
                ('', 'Espírito Santo     ', 3, ''), 
                ('', 'Goiás              ', 3, ''), 
                ('', 'Maranhão           ', 3, ''), 
                ('', 'Mato Grosso        ', 3, ''), 
                ('', 'Mato Grosso do Sul ', 3, ''), 
                ('', 'Minas Gerais       ', 3, ''), 
                ('', 'Paraná             ', 3, ''), 
                ('', 'Paraíba            ', 3, ''), 
                ('', 'Pará               ', 3, ''), 
                ('', 'Pernambuco         ', 3, ''), 
                ('', 'Piauí              ', 3, ''), 
                ('', 'Rio de Janeiro     ', 3, ''), 
                ('', 'Rio Grande do Norte', 3, ''), 
                ('', 'Rio Grande do Sul  ', 3, ''), 
                ('', 'Rondônia           ', 3, ''), 
                ('', 'Roraima            ', 3, ''), 
                ('', 'Santa Catarina     ', 3, ''), 
                ('', 'Sergipe            ', 3, ''), 
                ('', 'São Paulo          ', 3, ''), 
                ('', 'Tocantins          ', 3, ''), 
            
            -- Regiones de Chile (16 regiones)
                ('', 'Aisén del General Carlos Ibañez del Campo', 4, ''), 
                ('', 'Antofagasta                              ', 4, ''), 
                ('', 'Arica y Parinacota                       ', 4, ''), 
                ('', 'Atacama                                  ', 4, ''), 
                ('', 'Biobío                                   ', 4, ''), 
                ('', 'Coquimbo                                 ', 4, ''), 
                ('', 'La Araucanía                             ', 4, ''), 
                ('', 'Libertador General Bernardo O´Higgins    ', 4, ''), 
                ('', 'Los Lagos                                ', 4, ''), 
                ('', 'Los Ríos                                 ', 4, ''), 
                ('', 'Magallanes y de la Antártica Chilena     ', 4, ''), 
                ('', 'Maule                                    ', 4, ''), 
                ('', 'Región Metropolitana de Santiago         ', 4, ''), 
                ('', 'Tarapacá                                 ', 4, ''), 
                ('', 'Valparaíso                               ', 4, ''), 
                ('', 'Ñuble                                    ', 4, ''), 
            
            -- Departamentos de Colombia (33 departamentos)
                ('', 'Amazonas                ', 5, ''), 
                ('', 'Antioquia               ', 5, ''), 
                ('', 'Arauca                  ', 5, ''), 
                ('', 'Atlántico               ', 5, ''), 
                ('', 'Bogotá                  ', 5, ''), 
                ('', 'Bolívar                 ', 5, ''), 
                ('', 'Boyacá                  ', 5, ''), 
                ('', 'Caldas                  ', 5, ''), 
                ('', 'Caquetá                 ', 5, ''), 
                ('', 'Casanare                ', 5, ''), 
                ('', 'Cauca                   ', 5, ''), 
                ('', 'Cesar                   ', 5, ''), 
                ('', 'Chocó                   ', 5, ''), 
                ('', 'Cundinamarca            ', 5, ''), 
                ('', 'Córdoba                 ', 5, ''), 
                ('', 'Guainía                 ', 5, ''), 
                ('', 'Guaviare                ', 5, ''), 
                ('', 'Huila                   ', 5, ''), 
                ('', 'La Guajira              ', 5, ''), 
                ('', 'Magdalena               ', 5, ''), 
                ('', 'Meta                    ', 5, ''), 
                ('', 'Nariño                  ', 5, ''), 
                ('', 'Norte de Santander      ', 5, ''), 
                ('', 'Putumayo                ', 5, ''), 
                ('', 'Quindío                 ', 5, ''), 
                ('', 'Risaralda               ', 5, ''), 
                ('', 'San Andrés & Providencia', 5, ''), 
                ('', 'Santander               ', 5, ''), 
                ('', 'Sucre                   ', 5, ''), 
                ('', 'Tolima                  ', 5, ''), 
                ('', 'Valle del Cauca         ', 5, ''), 
                ('', 'Vaupés                  ', 5, ''), 
                ('', 'Vichada                 ', 5, ''), 

            -- Provincias de Ecuador (24 provincias)
                ('', 'Azuay                         ', 6, ''), 
                ('', 'Bolívar                       ', 6, ''), 
                ('', 'Carchi                        ', 6, ''), 
                ('', 'Cañar                         ', 6, ''), 
                ('', 'Chimborazo                    ', 6, ''), 
                ('', 'Cotopaxi                      ', 6, ''), 
                ('', 'El Oro                        ', 6, ''), 
                ('', 'Esmeraldas                    ', 6, ''), 
                ('', 'Galápagos                     ', 6, ''), 
                ('', 'Guayas                        ', 6, ''), 
                ('', 'Imbabura                      ', 6, ''), 
                ('', 'Loja                          ', 6, ''), 
                ('', 'Los Ríos                      ', 6, ''), 
                ('', 'Manabí                        ', 6, ''), 
                ('', 'Morona-Santiago               ', 6, ''), 
                ('', 'Napo                          ', 6, ''), 
                ('', 'Orellana                      ', 6, ''), 
                ('', 'Pastaza                       ', 6, ''), 
                ('', 'Pichincha                     ', 6, ''), 
                ('', 'Santa Elena                   ', 6, ''), 
                ('', 'Santo Domingo de los Tsáchilas', 6, ''), 
                ('', 'Sucumbíos                     ', 6, ''), 
                ('', 'Tungurahua                    ', 6, ''), 
                ('', 'Zamora-Chinchipe              ', 6, ''), 

            -- Parroquias & Territorios de Granada (14)
                ('', 'Isla Caille                        ', 7, ''), 
                ('', 'Isla de Carriacou/Cariobacú        ', 7, ''), 
                ('', 'Isla Diamante                      ', 7, ''), 
                ('', 'Isla Frigate                       ', 7, ''), 
                ('', 'Isla Larga                         ', 7, ''), 
                ('', 'Isla Ronde                         ', 7, ''), 
                ('', 'Isla Saline                        ', 7, ''), 
                ('', 'Petite Martinique/Pequeña Martinica', 7, ''), 
                ('', 'Saint Andrew                       ', 7, 'Parroquia'), 
                ('', 'Saint David                        ', 7, 'Parroquia'), 
                ('', 'Saint George                       ', 7, 'Parroquia'), 
                ('', 'Saint John                         ', 7, 'Parroquia'), 
                ('', 'Saint Mark                         ', 7, 'Parroquia'), 
                ('', 'Saint Patrick                      ', 7, 'Parroquia'), 

            -- Regiones de Guyana (10 regiones)
                ('', 'Alto Demerara-Berbice             ', 8, ''), 
                ('', 'Alto Tacutu-Alto Esequibo         ', 8, ''), 
                ('', 'Barima-Guainí                     ', 8, ''), 
                ('', 'Berbice Oriental-Corentyne        ', 8, ''), 
                ('', 'Cuyuní-Mazaruní                   ', 8, ''), 
                ('', 'Demerara-Mahaica                  ', 8, ''), 
                ('', 'Islas Esequibo-Demerara Occidental', 8, ''), 
                ('', 'Mahaica-Berbice                   ', 8, ''), 
                ('', 'Pomerón-Supenaam                  ', 8, ''), 
                ('', 'Potaro-Siparuní                   ', 8, ''), 

            -- Departamentos de Paraguay (18 departamentos)
                ('', 'Alto Paraguay   ', 9, ''), 
                ('', 'Alto Paraná     ', 9, ''), 
                ('', 'Amambay         ', 9, ''), 
                ('', 'Asunción        ', 9, ''), 
                ('', 'Boquerón        ', 9, ''), 
                ('', 'Caaguazú        ', 9, ''), 
                ('', 'Caazapá         ', 9, ''), 
                ('', 'Canindeyú       ', 9, ''), 
                ('', 'Central         ', 9, ''), 
                ('', 'Concepción      ', 9, ''), 
                ('', 'Cordillera      ', 9, ''), 
                ('', 'Guairá          ', 9, ''), 
                ('', 'Itapúa          ', 9, ''), 
                ('', 'Misiones        ', 9, ''), 
                ('', 'Ñeembucú        ', 9, ''), 
                ('', 'Paraguarí       ', 9, ''), 
                ('', 'Presidente Hayes', 9, ''), 
                ('', 'San Pedro       ', 9, ''), 

            -- Departamentos de Perú (26 departamentos)
                ('', 'Amazonas                           ', 10, ''), 
                ('', 'Áncash                             ', 10, ''), 
                ('', 'Apurímac                           ', 10, ''), 
                ('', 'Arequipa                           ', 10, ''), 
                ('', 'Ayacucho                           ', 10, ''), 
                ('', 'Cajamarca                          ', 10, ''), 
                ('', 'Callao                             ', 10, ''), 
                ('', 'Cuzco                              ', 10, ''), 
                ('', 'Huancavelica                       ', 10, ''), 
                ('', 'Huánuco                            ', 10, ''), 
                ('', 'Ica                                ', 10, ''), 
                ('', 'Junín                              ', 10, ''), 
                ('', 'La Libertad                        ', 10, ''), 
                ('', 'Lambayeque                         ', 10, ''), 
                ('', 'Lima                               ', 10, ''), 
                ('', 'Lima Metropolitana                 ', 10, ''), 
                ('', 'Loreto                             ', 10, ''), 
                ('', 'Madre de Dios                      ', 10, ''), 
                ('', 'Moquegua                           ', 10, ''), 
                ('', 'Pasco                              ', 10, ''), 
                ('', 'Piura                              ', 10, ''), 
                ('', 'Puno                               ', 10, ''), 
                ('', 'San Martín                         ', 10, ''), 
                ('', 'Tacna                              ', 10, ''), 
                ('', 'Tumbes                             ', 10, ''), 
                ('', 'Ucayali                            ', 10, ''), 

            -- Distritos/Districten de Surinam/Suriname (10 distritos)
                ('', 'Brokopondo', 11, ''), 
                ('', 'Commewijne', 11, ''), 
                ('', 'Coronie   ', 11, ''), 
                ('', 'Marowijne ', 11, ''), 
                ('', 'Nickerie  ', 11, ''), 
                ('', 'Para      ', 11, ''), 
                ('', 'Paramaribo', 11, ''), 
                ('', 'Saramacca ', 11, ''), 
                ('', 'Sipaliwini', 11, ''), 
                ('', 'Wanica    ', 11, ''), 

            -- Municipios, Regiones & Parroquias de Trinidad y Tobago (21)
                ('', 'Arima                  ', 12, 'Municipio de Trinidad'), 
                ('', 'Chaguanas              ', 12, 'Municipio de Trinidad'), 
                ('', 'Couva-Tabaquite-Talparo', 12, 'Región de Trinidad'), 
                ('', 'Diego Martín           ', 12, 'Región de Trinidad'), 
                ('', 'Penal-Debe             ', 12, 'Región de Trinidad'), 
                ('', 'Point Fortin           ', 12, 'Municipio de Trinidad'), 
                ('', 'Princes Town           ', 12, 'Región de Trinidad'), 
                ('', 'Puerto España          ', 12, 'Municipio de Trinidad'), 
                ('', 'Río Claro-Mayaro       ', 12, 'Región de Trinidad'), 
                ('', 'San Fernando           ', 12, 'Municipio de Trinidad'), 
                ('', 'San Juan-Laventille    ', 12, 'Región de Trinidad'), 
                ('', 'Sangre Grande          ', 12, 'Región de Trinidad'), 
                ('', 'Siparia                ', 12, 'Región de Trinidad'), 
                ('', 'St. Andrew             ', 12, 'Parroquia de Tobago'), 
                ('', 'St. David              ', 12, 'Parroquia de Tobago'), 
                ('', 'St. George             ', 12, 'Parroquia de Tobago'), 
                ('', 'St. John               ', 12, 'Parroquia de Tobago'), 
                ('', 'St. Mary               ', 12, 'Parroquia de Tobago'), 
                ('', 'St. Patrick            ', 12, 'Parroquia de Tobago'), 
                ('', 'St. Paul               ', 12, 'Parroquia de Tobago'), 
                ('', 'Tunapuna-Piarco        ', 12, 'Región de Trinidad'), 

            -- Departamentos de Uruguay (19 departamentos)
                ('', 'Artigas       ', 13, ''), 
                ('', 'Canelones     ', 13, ''), 
                ('', 'Cerro Largo   ', 13, ''), 
                ('', 'Colonia       ', 13, ''), 
                ('', 'Durazno       ', 13, ''), 
                ('', 'Flores        ', 13, ''), 
                ('', 'Florida       ', 13, ''), 
                ('', 'Lavalleja     ', 13, ''), 
                ('', 'Maldonado     ', 13, ''), 
                ('', 'Montevideo    ', 13, ''), 
                ('', 'Paysandú      ', 13, ''), 
                ('', 'Río Negro     ', 13, ''), 
                ('', 'Rivera        ', 13, ''), 
                ('', 'Rocha         ', 13, ''), 
                ('', 'Salto         ', 13, ''), 
                ('', 'San José      ', 13, ''), 
                ('', 'Soriano       ', 13, ''), 
                ('', 'Tacuarembó    ', 13, ''), 
                ('', 'Treinta y Tres', 13, ''), 

            -- Entidades Federales de Venezuela (25 entidades federales)
                ('', 'Amazonas              ', 14, ''), 
                ('', 'Anzoátegui            ', 14, ''), 
                ('', 'Apure                 ', 14, ''), 
                ('', 'Aragua                ', 14, ''), 
                ('', 'Barinas               ', 14, ''), 
                ('', 'Bolívar               ', 14, ''), 
                ('', 'Carabobo              ', 14, ''), 
                ('', 'Cojedes               ', 14, ''), 
                ('', 'Delta Amacuro         ', 14, ''), 
                ('', 'Dependencias federales', 14, ''), 
                ('', 'Distrito Capital      ', 14, ''), 
                ('', 'Falcón                ', 14, ''), 
                ('', 'Guárico               ', 14, ''), 
                ('', 'La Guaira             ', 14, ''), 
                ('', 'Lara                  ', 14, ''), 
                ('', 'Mérida                ', 14, ''), 
                ('', 'Miranda               ', 14, ''), 
                ('', 'Monagas               ', 14, ''), 
                ('', 'Nueva Esparta         ', 14, ''), 
                ('', 'Portuguesa            ', 14, ''), 
                ('', 'Sucre                 ', 14, ''), 
                ('', 'Trujillo              ', 14, ''), 
                ('', 'Táchira               ', 14, ''), 
                ('', 'Yaracuy               ', 14, ''), 
                ('', 'Zulia                 ', 14, ''), 
        -- No Soberanos
            -- Comunas de Guayana Francesa/Guyane/Guyane française (22 comunas)
                ('', 'Apatou                    ', 15, ''), 
                ('', 'Awala-Yalimapo            ', 15, ''), 
                ('', 'Camopi                    ', 15, ''), 
                ('', 'Cayena                    ', 15, ''), 
                ('', 'Grand-Santi               ', 15, ''), 
                ('', 'Iracoubo                  ', 15, ''), 
                ('', 'Kourou                    ', 15, ''), 
                ('', 'Macouria                  ', 15, ''), 
                ('', 'Mana                      ', 15, ''), 
                ('', 'Maripasoula               ', 15, ''), 
                ('', 'Matoury                   ', 15, ''), 
                ('', 'Montsinéry-Tonnegrande    ', 15, ''), 
                ('', 'Ouanary                   ', 15, ''), 
                ('', 'Papaïchton                ', 15, ''), 
                ('', 'Régina                    ', 15, ''), 
                ('', 'Remire-Montjoly           ', 15, ''), 
                ('', 'Roura                     ', 15, ''), 
                ('', 'Saint-Élie                ', 15, ''), 
                ('', 'Saint-Georges-de-l´Oyapock', 15, ''), 
                ('', 'Saint-Laurent-du-Maroni   ', 15, ''), 
                ('', 'Saül                      ', 15, ''), 
                ('', 'Sinnamary                 ', 15, ''), 
            
            -- Islas de Islas Georgias del Sur y Sandwich del Sur (31 islas)
                ('', 'Albatros         ', 16, 'Isla del grupo San Pedro'), 
                ('', 'Annenkov         ', 16, 'Isla del grupo San Pedro'), 
                ('', 'Bellingshausen   ', 16, 'Isla Tule del Sur'), 
                ('', 'Bristol          ', 16, 'Isla Central'), 
                ('', 'Candlemas        ', 16, 'Isla Candelaria'), 
                ('', 'Cook             ', 16, 'Isla Tule del Sur'), 
                ('', 'Cooper           ', 16, 'Isla del grupo San Pedro'), 
                ('', 'Grass            ', 16, 'Isla del grupo San Pedro'), 
                ('', 'Islas Bienvenido ', 16, 'Isla del grupo San Pedro'), 
                ('', 'Islas Kupriyanov ', 16, 'Isla del grupo San Pedro'), 
                ('', 'Islas Pickersgill', 16, 'Isla del grupo San Pedro'), 
                ('', 'Islas Willis     ', 16, 'Isla del grupo San Pedro'), 
                ('', 'Leskov           ', 16, 'Isla Traverse'), 
                ('', 'McCarthy         ', 16, 'Isla del grupo San Pedro'), 
                ('', 'Montagu          ', 16, 'Isla Central'), 
                ('', 'Pájaro           ', 16, 'Isla del grupo San Pedro'), 
                ('', 'Prión            ', 16, 'Isla del grupo San Pedro'), 
                ('', 'Roca Negra       ', 16, 'Islote Aurora'), 
                ('', 'Rocas Clerke     ', 16, ''), 
                ('', 'Rocas Cormorán   ', 16, 'Islote Aurora'), 
                ('', 'Rocas Negras     ', 16, 'Isla del grupo San Pedro'), 
                ('', 'Saddle           ', 16, 'Isla del grupo San Pedro'), 
                ('', 'Samuel           ', 16, 'Isla del grupo San Pedro'), 
                ('', 'Saunders         ', 16, 'Isla Central'), 
                ('', 'Thule/Morrell    ', 16, 'Isla Tule del Sur'), 
                ('', 'Trinidad         ', 16, 'Isla del grupo San Pedro'), 
                ('', 'Verde            ', 16, 'Isla del grupo San Pedro'), 
                ('', 'Vicent           ', 16, 'Isla del grupo San Pedro'), 
                ('', 'Vindication      ', 16, 'Isla Candelaria'), 
                ('', 'Visokoi          ', 16, 'Isla Traverse'), 
                ('', 'Zavodovski       ', 16, 'Isla Traverse'), 
            
            -- Islas Principales de Islas Malvinas (2 islas principales)
                ('', 'Gran Malvina', 17, ''), 
                ('', 'Isla Soledad', 17, ''), 
            
            -- Unidades Administrativas de Santa Elena, Ascensión y Tristán de Acuña (3 unidades administrativas)
                ('', 'Isla Ascensión  ', 18, ''), 
                ('', 'Santa Elena     ', 18, ''), 
                ('', 'Tristán de Acuña', 18, ''), 

    -- Provincias de Norteamérica
        -- Soberanos
            -- Provincias & Territorios de Canadá (13)
                ('', 'Alberta                  ', 19, ''), 
                ('', 'British Columbia         ', 19, ''), 
                ('', 'Manitoba                 ', 19, ''), 
                ('', 'New Brunswick            ', 19, ''), 
                ('', 'Newfoundland and Labrador', 19, ''), 
                ('', 'Northwest Territories    ', 19, ''), 
                ('', 'Nova Scotia              ', 19, ''), 
                ('', 'Nunavut                  ', 19, ''), 
                ('', 'Ontario                  ', 19, ''), 
                ('', 'Prince Edward Island     ', 19, ''), 
                ('', 'Québec                   ', 19, ''), 
                ('', 'Saskatchewan             ', 19, ''), 
                ('', 'Yukon                    ', 19, ''), 
            
            -- Estados de Estados Unidos (51 estados)
                ('', 'Alabama             ', 20, ''), 
                ('', 'Alaska              ', 20, ''), 
                ('', 'Arizona             ', 20, ''), 
                ('', 'Arkansas            ', 20, ''), 
                ('', 'California          ', 20, ''), 
                ('', 'Colorado            ', 20, ''), 
                ('', 'Connecticut         ', 20, ''), 
                ('', 'Delaware            ', 20, ''), 
                ('', 'District Of Columbia', 20, ''), 
                ('', 'Florida             ', 20, ''), 
                ('', 'Georgia             ', 20, ''), 
                ('', 'Hawaii              ', 20, ''), 
                ('', 'Idaho               ', 20, ''), 
                ('', 'Illinois            ', 20, ''), 
                ('', 'Indiana             ', 20, ''), 
                ('', 'Iowa                ', 20, ''), 
                ('', 'Kansas              ', 20, ''), 
                ('', 'Kentucky            ', 20, ''), 
                ('', 'Louisiana           ', 20, ''), 
                ('', 'Maine               ', 20, ''), 
                ('', 'Maryland            ', 20, ''), 
                ('', 'Massachusetts       ', 20, ''), 
                ('', 'Michigan            ', 20, ''), 
                ('', 'Minnesota           ', 20, ''), 
                ('', 'Mississippi         ', 20, ''), 
                ('', 'Missouri            ', 20, ''), 
                ('', 'Montana             ', 20, ''), 
                ('', 'Nebraska            ', 20, ''), 
                ('', 'Nevada              ', 20, ''), 
                ('', 'New Hampshire       ', 20, ''), 
                ('', 'New Jersey          ', 20, ''), 
                ('', 'New Mexico          ', 20, ''), 
                ('', 'New York            ', 20, ''), 
                ('', 'North Carolina      ', 20, ''), 
                ('', 'North Dakota        ', 20, ''), 
                ('', 'Ohio                ', 20, ''), 
                ('', 'Oklahoma            ', 20, ''), 
                ('', 'Oregon              ', 20, ''), 
                ('', 'Pennsylvania        ', 20, ''), 
                ('', 'Rhode Island        ', 20, ''), 
                ('', 'South Carolina      ', 20, ''), 
                ('', 'South Dakota        ', 20, ''), 
                ('', 'Tennessee           ', 20, ''), 
                ('', 'Texas               ', 20, ''), 
                ('', 'Utah                ', 20, ''), 
                ('', 'Vermont             ', 20, ''), 
                ('', 'Virginia            ', 20, ''), 
                ('', 'Washington          ', 20, ''), 
                ('', 'West Virginia       ', 20, ''), 
                ('', 'Wisconsin           ', 20, ''), 
                ('', 'Wyoming             ', 20, ''), 
            
            -- Entidades federativas/Estados de México (32 entidades)
                ('', 'Aguascalientes                 ', 21, ''), 
                ('', 'Baja California                ', 21, ''), 
                ('', 'Baja California Sur            ', 21, ''), 
                ('', 'Campeche                       ', 21, ''), 
                ('', 'Chiapas                        ', 21, ''), 
                ('', 'Chihuahua                      ', 21, ''), 
                ('', 'Ciudad de México               ', 21, ''), 
                ('', 'Coahuila de Zaragoza           ', 21, ''), 
                ('', 'Colima                         ', 21, ''), 
                ('', 'Durango                        ', 21, ''), 
                ('', 'Guanajuato                     ', 21, ''), 
                ('', 'Guerrero                       ', 21, ''), 
                ('', 'Hidalgo                        ', 21, ''), 
                ('', 'Jalisco                        ', 21, ''), 
                ('', 'Michoacán de Ocampo            ', 21, ''), 
                ('', 'Morelos                        ', 21, ''), 
                ('', 'México                         ', 21, ''), 
                ('', 'Nayarit                        ', 21, ''), 
                ('', 'Nuevo León                     ', 21, ''), 
                ('', 'Oaxaca                         ', 21, ''), 
                ('', 'Puebla                         ', 21, ''), 
                ('', 'Querétaro                      ', 21, ''), 
                ('', 'Quintana Roo                   ', 21, ''), 
                ('', 'San Luis Potosí                ', 21, ''), 
                ('', 'Sinaloa                        ', 21, ''), 
                ('', 'Sonora                         ', 21, ''), 
                ('', 'Tabasco                        ', 21, ''), 
                ('', 'Tamaulipas                     ', 21, ''), 
                ('', 'Tlaxcala                       ', 21, ''), 
                ('', 'Veracruz de Ignacio de la Llave', 21, ''), 
                ('', 'Yucatán                        ', 21, ''), 
                ('', 'Zacatecas                      ', 21, ''), 
